/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.zhangxiaoxiao.spring.mvc.learn;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
